//
//  GeneratedImage.swift
//  Yondo
//
//  Created by Andrei Marincas on 30.12.2025.
//

import Foundation

/// Represents an image generated by the AI, with metadata for identification and creation time.
struct GeneratedImage: Identifiable, Codable, Equatable, Hashable {
    /// Unique identifier for the generated image.
    let id: UUID
    /// Filename where the generated image is stored.
    let filename: String
    /// Date and time when the image was created.
    let createdAt: Date
}

extension GeneratedImage {
    /// Convenience initializer to create a new GeneratedImage with a filename,
    /// automatically generating a UUID and setting the creation date to now.
    /// - Parameter filename: The filename for the generated image.
    init(filename: String) {
        self.id = UUID()
        self.filename = filename
        self.createdAt = Date()
    }
}
