//
//  SceneGenerationError.swift
//  Yondo
//
//  Created by Andrei Marincas on 24.03.2026.
//

import Foundation

enum SceneGenerationError: LocalizedError, Equatable {
    
    // Premium specific
    case requiresPremiumUnlock(destinationName: String?)
    case syncingPremiumUnlock
    
    // Credit specific
    case insufficientCredits
    case syncingCredits
    
    // Generation/Network specific
    case aiBusy
    case networkConnectionLost
    
    // Catch-all
    case unknown(Error)
    
    static func == (lhs: SceneGenerationError, rhs: SceneGenerationError) -> Bool {
        switch (lhs, rhs) {
        case (.requiresPremiumUnlock(let lDest), .requiresPremiumUnlock(let rDest)):
            return lDest == rDest
        case (.syncingPremiumUnlock, .syncingPremiumUnlock),
             (.insufficientCredits, .insufficientCredits),
             (.syncingCredits, .syncingCredits),
             (.aiBusy, .aiBusy),
             (.networkConnectionLost, .networkConnectionLost):
            return true
        case (.unknown(let lErr), .unknown(let rErr)):
            return (lErr as NSError) == (rErr as NSError)
        default:
            return false
        }
    }
    
    var errorDescription: String? {
        switch self {
        case .requiresPremiumUnlock(let destinationName):
            let name = destinationName ?? "This destination"
            return "\(name) requires a Premium Unlock to visit."
        case .syncingPremiumUnlock, .syncingCredits:
            return "Updating your balance... this should only take a moment."
        case .insufficientCredits:
            return "You'll need more credits to generate this Yondo."
        case .aiBusy:
            return "The AI engine is currently busy. Please try again in a moment."
        case .networkConnectionLost:
            return "Connection lost. Please check your internet and try again."
        case .unknown(let error):
            // For production, you might want to hide raw localizedDescriptions from users
            // unless they are explicitly generated by your own domain logic.
            return "Something went wrong. Please try again."
//            return error.localizedDescription
        }
    }
    
    var isSyncing: Bool {
        switch self {
        case .syncingCredits, .syncingPremiumUnlock: return true
        default: return false
        }
    }
    
    var isInsufficient: Bool {
        switch self {
        case .insufficientCredits, .requiresPremiumUnlock: return true
        default: return false
        }
    }
}
